{pageaddvar name='jsgettext' value='module_clip_js:Clip'}
{ajaxheader filename='Zikula.Clip.Container.js' ui=true}
{pageaddvar name='javascript' value='modules/Clip/javascript/Clip.Pubtype.js'}
{pageaddvar name='javascript' value='modules/Clip/javascript/Clip.Pubfields.js'}
{pageaddvar name='stylesheet' value='system/Theme/style/pagercss.css'}

{include file='clip_admin_header.tpl'}

<div id="clip_cols_container">
    <div id="clip_cols_sidecol">
        <p id="groupControls" class="z-hide">
            <a href="#" id="groupNew">{gt text='Add group'}</a>
            |
            <a href="#" id="groupExpand">{gt text='Expand'}</a>
            |
            <a href="#" id="groupCollapse">{gt text='Collapse'}</a>
        </p>
        {$treejscode}
    </div>

    <div id="clip_cols_maincol">
        <div id="clip_cols_indicator" class="z-window-indicator" style="display: none"></div>
        <div id="clip_cols_maincontent">
            <h3>{gt text='Admin Panel'}</h3>
            <h4>{gt text='About Clip'}</h4>
            {gettext}
            <p>Clip is one of the <strong>must have</strong> Zikula modules. It let you manage any type of estructured content or media in your Zikula website.</p>
            <p>To use its potential, you just need to know what do you need in detail; let's suppose you need a News system. Then your Publication Type can be named "News" and its <em>Publications</em> will be Articles.
            For each article, you need a title, a summary, a complete text and a category.</p>
            <p>The process to configure this "News" publication type is really simple:</p>
            <ol>
                <li>Use the <em>New Publication Type</em> button, setup the desired name, according with your requirements configure the options that Clip offers, and setup the folder where you will put its contents.</li>
                <li>After press the 'Create' button, you will be directed to a screen where you can setup the <em>Publication Fields</em>. You can add now the fields required by your Articles:<br />
                For each name, choose a Name (used internally by Clip), a Public Name (Displayed in the Edit Form and probably in the Article too) and the rest. You can consult each form help for more details.</li>
                <li>Next, you can setup the <em>Relations</em> of your articles with other <em>Publication Types</em> if you want.</li>
                <li>The last step is to build the <em>Templates</em> for your data, starting from the code generated by Clip for you. With some HTML and Smarty knowledge, you will be able to do whatever you want with them.
                You can customize them to suit your needs, and put them in the specified paths. You can use the autogenerated templates while you get familiar with them.</li>
                <li>Ready! You can add Articles, filter it lists, and stablish permissions to let the require groups to submit stuff.</li>
                <li>Enjoy and Share your experiences!</li>
            </ol>
            {/gettext}
            <h4>{gt text='About this Index'}</h4>
            {gettext}
            <p>Clip let you organize your Publication Types through Groups. At the left side, you can manage and order all of them to feel confortable.</p>
            <p>By clicking a <em>Publication Type</em> you will get its details and available options loaded dynamically. You can right click the elements of the tree to see their options too.</p>
            {/gettext}
        </div>
    </div>
</div>
{adminfooter}
